package types

type SearchResult struct {
	Name     string `json:"name"`
	Category string `json:"category"`
}

type Results struct {
	Results []SearchResult `json:"results"`
}

type Weapons struct {
	Weapons []*Weapon `json:"weapons"`
}

type Weapon struct {
	ID                                      string `json:"id" bson:"id"`
	Category                                string `json:"category,omitempty" bson:"category,omitempty"`
	Name                                    string `json:"name,omitempty" bson:"name,omitempty"`
	Mass                                    string `json:"mass,omitempty" bson:"mass,omitempty"`
	MassAtEndOfBoosterBurn                  string `json:"mass_at_end_of_booster_burn,omitempty" bson:"mass_at_end_of_booster_burn,omitempty"`
	MassAtEndOfSustainerBurn                string `json:"mass_at_end_of_sustainer_burn,omitempty" bson:"mass_at_end_of_sustainer_burn,omitempty"`
	Caliber                                 string `json:"caliber,omitempty" bson:"caliber,omitempty"`
	Length                                  string `json:"length,omitempty" bson:"length,omitempty"`
	ForceExertedByBooster                   string `json:"force_exerted_by_booster,omitempty" bson:"force_exerted_by_booster,omitempty"`
	BurnTimeOfBooster                       string `json:"burn_time_of_booster,omitempty" bson:"burn_time_of_booster,omitempty"`
	RawAccelerationAtIgnition               string `json:"raw_acceleration_at_ignition,omitempty" bson:"raw_acceleration_at_ignition,omitempty"`
	SpecificImpulseOfBooster                string `json:"specific_impulse_of_booster,omitempty" bson:"specific_impulse_of_booster,omitempty"`
	DeltaVOfBooster                         string `json:"delta_v_of_booster,omitempty" bson:"delta_v_of_booster,omitempty"`
	BoosterStartDelay                       string `json:"booster_start_delay,omitempty" bson:"booster_start_delay,omitempty"`
	ForceExertedBySustainer                 string `json:"force_exerted_by_sustainer,omitempty" bson:"force_exerted_by_sustainer,omitempty"`
	BurnTimeOfSustainer                     string `json:"burn_time_of_sustainer,omitempty" bson:"burn_time_of_sustainer,omitempty"`
	SpecificImpulseOfSustainer              string `json:"specific_impulse_of_sustainer,omitempty" bson:"specific_impulse_of_sustainer,omitempty"`
	DeltaVOfSustainer                       string `json:"delta_v_of_sustainer,omitempty" bson:"delta_v_of_sustainer,omitempty"`
	TotalDeltaV                             string `json:"total_delta_v,omitempty" bson:"total_delta_v,omitempty"`
	ExplosiveMass                           string `json:"explosive_mass,omitempty" bson:"explosive_mass,omitempty"`
	Warhead                                 string `json:"warhead,omitempty" bson:"warhead,omitempty"`
	Penetration                             string `json:"penetration,omitempty" bson:"penetration,omitempty"`
	ProximityFuse                           string `json:"proximity_fuse,omitempty" bson:"proximity_fuse,omitempty"`
	ProximityFuseArmingDistance             string `json:"proximity_fuse_arming_distance,omitempty" bson:"proximity_fuse_arming_distance,omitempty"`
	ProximityFuseArmingDistanceFromTarget   string `json:"proximity_fuse_arming_distance_from_target,omitempty" bson:"proximity_fuse_arming_distance_from_target,omitempty"`
	ProximityFuseRange                      string `json:"proximity_fuse_range,omitempty" bson:"proximity_fuse_range,omitempty"`
	ProximityFuseShellDetection             string `json:"proximity_fuse_shell_detection,omitempty" bson:"proximity_fuse_shell_detection,omitempty"`
	ProximityFuseMinimumAltitude            string `json:"proximity_fuse_minimum_altitude,omitempty" bson:"proximity_fuse_minimum_altitude,omitempty"`
	ProximityFuseDelay                      string `json:"proximity_fuse_delay,omitempty" bson:"proximity_fuse_delay,omitempty"`
	ImpactFuseSensitivity                   string `json:"impact_fuse_sensitivity,omitempty" bson:"impact_fuse_sensitivity,omitempty"`
	ImpactFuseDelay                         string `json:"impact_fuse_delay,omitempty" bson:"impact_fuse_delay,omitempty"`
	DefaultZoom                             string `json:"default_zoom,omitempty" bson:"default_zoom,omitempty"`
	GuidanceType                            string `json:"guidance_type,omitempty" bson:"guidance_type,omitempty"`
	GuidanceStartDelay                      string `json:"guidance_start_delay,omitempty" bson:"guidance_start_delay,omitempty"`
	GuidanceDuration                        string `json:"guidance_duration,omitempty" bson:"guidance_duration,omitempty"`
	GuidanceRange                           string `json:"guidance_range,omitempty" bson:"guidance_range,omitempty"`
	GuidanceFOV                             string `json:"guidance_fov,omitempty" bson:"guidance_fov,omitempty"`
	GuidanceMaxLead                         string `json:"guidance_max_lead,omitempty" bson:"guidance_max_lead,omitempty"`
	LaunchSector                            string `json:"launch_sector,omitempty" bson:"launch_sector,omitempty"`
	GuidanceLaunchSector                    string `json:"guidance_launch_sector,omitempty" bson:"guidance_launch_sector,omitempty"`
	AimTrackingSensitivity                  string `json:"aim_tracking_sensitivity,omitempty" bson:"aim_tracking_sensitivity,omitempty"`
	SeekerWarmUpTime                        string `json:"seeker_warm_up_time,omitempty" bson:"seeker_warm_up_time,omitempty"`
	SeekerSearchDuration                    string `json:"seeker_search_duration,omitempty" bson:"seeker_search_duration,omitempty"`
	SeekerRange                             string `json:"seeker_range,omitempty" bson:"seeker_range,omitempty"`
	FieldOfView                             string `json:"field_of_view,omitempty" bson:"field_of_view,omitempty"`
	GimbalLimit                             string `json:"gimbal_limit,omitempty" bson:"gimbal_limit,omitempty"`
	TrackRate                               string `json:"track_rate,omitempty" bson:"track_rate,omitempty"`
	UncagedSeekerBeforeLaunch               string `json:"uncaged_seeker_before_launch,omitempty" bson:"uncaged_seeker_before_launch,omitempty"`
	MaxLockAngleBeforeLaunch                string `json:"max_lock_angle_before_launch,omitempty" bson:"max_lock_angle_before_launch,omitempty"`
	MinAngleOfIncidenceToSun                string `json:"min_angle_of_incidence_to_sun,omitempty" bson:"min_angle_of_incidence_to_sun,omitempty"`
	BaselineLockRangeRear                   string `json:"baseline_lock_range_rear,omitempty" bson:"baseline_lock_range_rear,omitempty"`
	BaselineFlareAndIRCMDetectionRange      string `json:"baseline_flare_and_ircm_detection_range,omitempty" bson:"baseline_flare_and_ircm_detection_range,omitempty"`
	BaselineLockRangeAll                    string `json:"baseline_lock_range_all,omitempty" bson:"baseline_lock_range_all,omitempty"`
	BaselineLockRangeGround                 string `json:"baseline_lock_range_ground,omitempty" bson:"baseline_lock_range_ground,omitempty"`
	BaselineLockRangeTarget                 string `json:"baseline_lock_range_target,omitempty" bson:"baseline_lock_range_target,omitempty"`
	BaselineFlareDetection                  string `json:"baseline_flare_detection,omitempty" bson:"baseline_flare_detection,omitempty"`
	BaselineIRCMDetection                   string `json:"baseline_ircm_detection,omitempty" bson:"baseline_ircm_detection,omitempty"`
	BaselineDIRCMDetection                  string `json:"baseline_dircm_detection,omitempty" bson:"baseline_dircm_detection,omitempty"`
	BaselineLDIRCMDetection                 string `json:"baseline_ldircm_detection,omitempty" bson:"baseline_ldircm_detection,omitempty"`
	BaselineHeadOnLockRange                 string `json:"baseline_head_on_lock_range,omitempty" bson:"baseline_head_on_lock_range,omitempty"`
	MaxLockRangeHardLimit                   string `json:"max_lock_range,omitempty" bson:"max_lock_range,omitempty"`
	IRCCM                                   string `json:"irccm,omitempty" bson:"irccm,omitempty"`
	IRCCMType                               string `json:"irccm_type,omitempty" bson:"irccm_type,omitempty"`
	IRCCMFieldOfView                        string `json:"irccm_field_of_view,omitempty" bson:"irccm_field_of_view,omitempty"`
	IRCCMRejectionThreshold                 string `json:"irccm_rejection_threshold,omitempty" bson:"irccm_rejection_threshold,omitempty"`
	IRCCMReactionTime                       string `json:"irccm_reaction_time,omitempty" bson:"irccm_reaction_time,omitempty"`
	MinTargetSize                           string `json:"min_target_size,omitempty" bson:"min_target_size,omitempty"`
	MaxBreakLockTime                        string `json:"max_break_lock_time,omitempty" bson:"max_break_lock_time,omitempty"`
	CanBeSlavedToRadar                      string `json:"can_be_slaved_to_radar,omitempty" bson:"can_be_slaved_to_radar,omitempty"`
	CanLockAfterLaunch                      string `json:"can_lock_after_launch,omitempty" bson:"can_lock_after_launch,omitempty"`
	Band                                    string `json:"band,omitempty" bson:"band,omitempty"`
	AngularSpeedRejectionThresh             string `json:"angular_speed_rejection,omitempty" bson:"angular_speed_rejection,omitempty"`
	AccelRejectionThreshRange               string `json:"accel_rejection,omitempty" bson:"accel_rejection,omitempty"`
	InertialGuidanceDriftSpeedMs            string `json:"inertial_guidance_drift_ms,omitempty" bson:"inertial_guidance_drift_ms,omitempty"`
	InertialGuidanceDriftSpeed              string `json:"inertial_guidance_drift,omitempty" bson:"inertial_guidance_drift,omitempty"`
	Datalink                                string `json:"datalink,omitempty" bson:"datalink,omitempty"`
	CanDatalinkReconnect                    string `json:"can_datalink_reconnect,omitempty" bson:"can_datalink_reconnect,omitempty"`
	SidelobeAttenuation                     string `json:"sidelobe_attenuation,omitempty" bson:"sidelobe_attenuation,omitempty"`
	TransmitterPower                        string `json:"transmitter_power,omitempty" bson:"transmitter_power,omitempty"`
	TransmitterHalfSensitivity              string `json:"transmitter_half_sensitivity,omitempty" bson:"transmitter_half_sensitivity,omitempty"`
	TransmitterSidelobeSens                 string `json:"transmitter_sidelobe_sensitivity,omitempty" bson:"transmitter_sidelobe_sensitivity,omitempty"`
	ReceiverHalfSensitivity                 string `json:"receiver_half_sensitivity,omitempty" bson:"receiver_half_sensitivity,omitempty"`
	ReceiverSidelobeSens                    string `json:"receiver_sidelobe_sensitivity,omitempty" bson:"receiver_sidelobe_sensitivity,omitempty"`
	DistanceMinValue                        string `json:"distance_min,omitempty" bson:"distance_min,omitempty"`
	DistanceMaxValue                        string `json:"distance_max,omitempty" bson:"distance_max,omitempty"`
	DistanceWidth                           string `json:"distance_width,omitempty" bson:"distance_width,omitempty"`
	DistanceRefWidth                        string `json:"distance_ref_width,omitempty" bson:"distance_ref_width,omitempty"`
	DistanceMinSignalGate                   string `json:"distance_min_signal_gate,omitempty" bson:"distance_min_signal_gate,omitempty"`
	DistanceMinValueM                       string `json:"distance_min_m,omitempty" bson:"distance_min_m,omitempty"`
	DistanceMaxValueKm                      string `json:"distance_max_km,omitempty" bson:"distance_max_km,omitempty"`
	DistanceWidthM                          string `json:"distance_width_m,omitempty" bson:"distance_width_m,omitempty"`
	DistanceRefWidthM                       string `json:"distance_ref_width_m,omitempty" bson:"distance_ref_width_m,omitempty"`
	DistanceMinSignalGateM                  string `json:"distance_min_signal_gate_m,omitempty" bson:"distance_min_signal_gate_m,omitempty"`
	DistanceGateSearchRange                 string `json:"distance_gate_search,omitempty" bson:"distance_gate_search,omitempty"`
	DistanceGateAlphaFilter                 string `json:"distance_gate_alpha,omitempty" bson:"distance_gate_alpha,omitempty"`
	DistanceGateBetaFilter                  string `json:"distance_gate_beta,omitempty" bson:"distance_gate_beta,omitempty"`
	DopplerSpeedMinValue                    string `json:"doppler_speed_min,omitempty" bson:"doppler_speed_min,omitempty"`
	DopplerSpeedMaxValue                    string `json:"doppler_speed_max,omitempty" bson:"doppler_speed_max,omitempty"`
	DopplerSpeedWidth                       string `json:"doppler_speed_width,omitempty" bson:"doppler_speed_width,omitempty"`
	DopplerSpeedRefWidth                    string `json:"doppler_speed_ref_width,omitempty" bson:"doppler_speed_ref_width,omitempty"`
	DopplerSpeedMinSignalGate               string `json:"doppler_speed_min_gate,omitempty" bson:"doppler_speed_min_gate,omitempty"`
	DopplerSpeedGateSearch                  string `json:"doppler_speed_gate_search,omitempty" bson:"doppler_speed_gate_search,omitempty"`
	DopplerSpeedGateAlpha                   string `json:"doppler_speed_gate_alpha,omitempty" bson:"doppler_speed_gate_alpha,omitempty"`
	DopplerSpeedGateBeta                    string `json:"doppler_speed_gate_beta,omitempty" bson:"doppler_speed_gate_beta,omitempty"`
	ProportionalNavMultiplier               string `json:"proportional_nav_multiplier,omitempty" bson:"proportional_nav_multiplier,omitempty"`
	BaseIndicatedAirSpeed                   string `json:"base_air_speed,omitempty" bson:"base_air_speed,omitempty"`
	PIDProportionalTerm                     string `json:"pid_proportional,omitempty" bson:"pid_proportional,omitempty"`
	PIDIntegralTerm                         string `json:"pid_integral,omitempty" bson:"pid_integral,omitempty"`
	PIDIntegralTermLimit                    string `json:"pid_integral_limit,omitempty" bson:"pid_integral_limit,omitempty"`
	PIDDerivativeTerm                       string `json:"pid_derivative,omitempty" bson:"pid_derivative,omitempty"`
	OrientingPhase                          string `json:"orienting_phase,omitempty" bson:"orienting_phase,omitempty"`
	OrientingStartDelay                     string `json:"orienting_start_delay,omitempty" bson:"orienting_start_delay,omitempty"`
	OrientingControlTime                    string `json:"orienting_control_time,omitempty" bson:"orienting_control_time,omitempty"`
	OrientingElevationAddition              string `json:"orienting_elevation_addition,omitempty" bson:"orienting_elevation_addition,omitempty"`
	DragCoefficientMultiplier               string `json:"drag_coefficient_multiplier,omitempty" bson:"drag_coefficient_multiplier,omitempty"`
	DragCoefficientMultiplierBomb           string `json:"drag_coefficient_multiplier_bomb,omitempty" bson:"drag_coefficient_multiplier_bomb,omitempty"`
	WingAreaMultiplier                      string `json:"wing_area_multiplier,omitempty" bson:"wing_area_multiplier,omitempty"`
	StartSpeed                              string `json:"start_speed,omitempty" bson:"start_speed,omitempty"`
	MaximumSpeed                            string `json:"maximum_speed,omitempty" bson:"maximum_speed,omitempty"`
	MinimumRange                            string `json:"minimum_range,omitempty" bson:"minimum_range,omitempty"`
	MinimumRangeKm                          string `json:"minimum_range_km,omitempty" bson:"minimum_range_km,omitempty"`
	FlightRangeLimit                        string `json:"flight_range_limit,omitempty" bson:"flight_range_limit,omitempty"`
	MaximumGLoad                            string `json:"maximum_g_load,omitempty" bson:"maximum_g_load,omitempty"`
	MaximumFinAngleOfAttack                 string `json:"maximum_fin_angle_of_attack,omitempty" bson:"maximum_fin_angle_of_attack,omitempty"`
	MaximumFinLateralAcceleration           string `json:"maximum_fin_lateral_acceleration,omitempty" bson:"maximum_fin_lateral_acceleration,omitempty"`
	FinsLateralAcceleration                 string `json:"fins_lateral_acceleration,omitempty" bson:"fins_lateral_acceleration,omitempty"`
	MaximumLateralAcceleration              string `json:"maximum_lateral_acceleration,omitempty" bson:"maximum_lateral_acceleration,omitempty"`
	MaxLateralAcceleration                  string `json:"max_lateral_acceleration,omitempty" bson:"max_lateral_acceleration,omitempty"`
	MaximumAOA                              string `json:"maximum_aoa,omitempty" bson:"maximum_aoa,omitempty"`
	ThrustVectoring                         string `json:"thrust_vectoring,omitempty" bson:"thrust_vectoring,omitempty"`
	ThrustVectoringAngle                    string `json:"thrust_vectoring_angle,omitempty" bson:"thrust_vectoring_angle,omitempty"`
	ThrustVectoringAngles                   string `json:"thrust_vectoring_angles,omitempty" bson:"thrust_vectoring_angles,omitempty"`
	MaximumLaunchAngleHorizontalVertical    string `json:"maximum_launch_angle_horizontal_vertical,omitempty" bson:"maximum_launch_angle_horizontal_vertical,omitempty"`
	MaximumLaunchAngle                      string `json:"maximum_launch_angle,omitempty" bson:"maximum_launch_angle,omitempty"`
	MaximumAxisValues                       string `json:"maximum_axis_values,omitempty" bson:"maximum_axis_values,omitempty"`
	StatcardSpeedMach                       string `json:"statcard_speed_mach,omitempty" bson:"statcard_speed_mach,omitempty"`
	StatcardSpeedMs                         string `json:"statcard_speed_ms,omitempty" bson:"statcard_speed_ms,omitempty"`
	StatcardSpeedMsOrMach                   string `json:"statcard_speed_ms_or_mach,omitempty" bson:"statcard_speed_ms_or_mach,omitempty"`
	StatcardLaunchRange                     string `json:"statcard_launch_range,omitempty" bson:"statcard_launch_range,omitempty"`
	StatcardGuaranteedRange                 string `json:"statcard_guaranteed_range,omitempty" bson:"statcard_guaranteed_range,omitempty"`
	MaximumStatcardGLoad                    string `json:"maximum_statcard_g_load,omitempty" bson:"maximum_statcard_g_load,omitempty"`
	StatcardMaxGLoad                        string `json:"statcard_max_g_load,omitempty" bson:"statcard_max_g_load,omitempty"`
	FlightTimeUntilGuidanceStarts           string `json:"flight_time_until_guidance_starts,omitempty" bson:"flight_time_until_guidance_starts,omitempty"`
	FlightTimeWhenPullLimitX                string `json:"flight_time_when_pull_limit_x,omitempty" bson:"flight_time_when_pull_limit_x,omitempty"`
	FlightTimeWhenPullLimit100              string `json:"flight_time_when_pull_limit_100,omitempty" bson:"flight_time_when_pull_limit_100,omitempty"`
	ETAtoImpactWhenPropMultiplier           string `json:"eta_to_impact_when_prop_multiplier,omitempty" bson:"eta_to_impact_when_prop_multiplier,omitempty"`
	Loft                                    string `json:"loft,omitempty" bson:"loft,omitempty"`
	LoftAngle                               string `json:"loft_angle,omitempty" bson:"loft_angle,omitempty"`
	LoftA                                   string `json:"loft_a,omitempty" bson:"loft_a,omitempty"`
	TargetElevation                         string `json:"target_elevation,omitempty" bson:"target_elevation,omitempty"`
	TargetE                                 string `json:"target_e,omitempty" bson:"target_e,omitempty"`
	MaximumTargetAngularChange              string `json:"maximum_target_angular_change,omitempty" bson:"maximum_target_angular_change,omitempty"`
	HasTracerInTail                         string `json:"has_tracer_in_tail,omitempty" bson:"has_tracer_in_tail,omitempty"`
	SeaSkimming                             string `json:"sea_skimming,omitempty" bson:"sea_skimming,omitempty"`
	ETAtoImpactWhenSeaAltitudeReachesMetres string `json:"eta_to_impact_when_sea_altitude_reaches_metres,omitempty" bson:"eta_to_impact_when_sea_altitude_reaches_metres,omitempty"`
	SkimAltitude                            string `json:"skim_altitude,omitempty" bson:"skim_altitude,omitempty"`
	AttackAltitude                          string `json:"attack_altitude,omitempty" bson:"attack_altitude,omitempty"`
	AdditionalNotes                         string `json:"additional_notes,omitempty" bson:"additional_notes,omitempty"`
}
