export const WEAPONS_CATEGORIES = [
  { value: "aam-ir-rear-aspect", label: "AAM (IR rear-aspect)" },
  { value: "aam-ir-all-aspect", label: "AAM (IR all-aspect)" },
  { value: "aam-ir-heli", label: "AAM (IR heli)" },
  { value: "aam-sarh", label: "AAM (SARH)" },
  { value: "aam-arh", label: "AAM (ARH)" },
  { value: "aam-manual", label: "AAM (Manual)" },
  { value: "agm-tv", label: "AGM (TV)" },
  { value: "agm-ir", label: "AGM (IR)" },
  { value: "agm-gnss", label: "AGM (GNSS)" },
  { value: "agm-salh", label: "AGM (SALH)" },
  { value: "agm-losbr", label: "AGM (LOSBR)" },
  { value: "agm-saclos", label: "AGM (SACLOS)" },
  { value: "agm-mclos", label: "AGM (MCLOS)" },
  { value: "gbu-tv", label: "GBU (TV)" },
  { value: "gbu-ir", label: "GBU (IR)" },
  { value: "gbu-gnss", label: "GBU (GNSS)" },
  { value: "gbu-salh", label: "GBU (SALH)" },
  { value: "sam-arh", label: "SAM (ARH)" },
  { value: "sam-ir", label: "SAM (IR)" },
  { value: "sam-ir-optical", label: "SAM (IR/OPTICAL)" },
  { value: "sam-losbr", label: "SAM (LOSBR)" },
  { value: "sam-saclos", label: "SAM (SACLOS)" },
  { value: "atgm-ir", label: "ATGM (IR)" },
  { value: "atgm-losbr", label: "ATGM (LOSBR)" },
  { value: "atgm-saclos", label: "ATGM (SACLOS)" },
  { value: "atgm-mclos", label: "ATGM (MCLOS)" },
  { value: "ashm-arh", label: "AShM (ARH)" },
  { value: "ashm-saclos", label: "AShM (SACLOS)" },
  { value: "sam-ir-naval", label: "SAM (IR) (naval)" },
  { value: "sam-saclos-naval", label: "SAM (SACLOS) (naval)" },
];
