name: CI 

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.1"

      - name: Run unit tests
        run: go test -short ./...
      
      - name: Run linter
        run: go vet ./...
